services:
  grafana-snapshots:
    image: grafana-snapshots:v0.1.0
    environment:
      GRAFANA_URL: http://host.docker.internal:3000
      GRAFANA_USER: admin
      GRAFANA_PASSWORD: admin
      GRAFANA_DASHBOARD_UID: snapshot-demo
    volumes:
      - ./reports:/reports
